/* eslint-disable @next/next/no-img-element */
"use client";

import { useState } from "react";
import Link from "next/link";
import { ArrowLeft, Check, Clipboard, Download, ImagePlus, LoaderCircle, Sparkles } from "lucide-react";
import type { GenerationRecord, GenerationType } from "@/lib/schemas";

const purposes = [["new_menu","신메뉴 소개"],["event","이벤트 안내"],["daily","일상 소식"],["notice","공지사항"]] as const;
const noticeTypes = [["wifi","와이파이"],["restroom","화장실"],["parking","주차"],["hours","영업시간"],["order_guide","주문 방법"]] as const;
const config = {
  copy: { eyebrow: "글쓰기", title: "홍보 문구 만들기", description: "전하고 싶은 핵심만 적어주세요. 채널에 딱 맞는 문구 3가지를 제안해드려요." },
  image: { eyebrow: "디자인", title: "홍보 이미지 만들기", description: "좋은 사진 한 장이면 충분해요. 사진은 그대로 두고 잘 어울리는 문구와 배치를 제안해드려요." },
  notice: { eyebrow: "매장 운영", title: "매장 안내물 만들기", description: "안내할 내용을 적으면 손님이 한눈에 이해하는 깔끔한 안내문을 만들어요." },
};

type Option = Record<string, unknown>;

export function GenerationStudio({ type }: { type: GenerationType }) {
  const [purpose, setPurpose] = useState("new_menu"); const [channel, setChannel] = useState("instagram");
  const [message, setMessage] = useState(""); const [noticeType, setNoticeType] = useState("wifi");
  const [details, setDetails] = useState(""); const [title, setTitle] = useState(""); const [dateText, setDateText] = useState("");
  const [photoPath, setPhotoPath] = useState<string | null>(null); const [photoUrl, setPhotoUrl] = useState<string | null>(null);
  const [loading, setLoading] = useState(false); const [uploading, setUploading] = useState(false); const [error, setError] = useState("");
  const [record, setRecord] = useState<GenerationRecord | null>(null); const [selected, setSelected] = useState<number | null>(null); const [copied, setCopied] = useState<number | null>(null);
  const info = config[type];

  async function upload(file: File) { setUploading(true); setError(""); try { const form = new FormData(); form.append("file", file); const response = await fetch("/api/uploads", { method: "POST", body: form }); const json = await response.json(); if (!json.ok) throw new Error(json.error); setPhotoPath(json.data.storedName); setPhotoUrl(json.data.url); } catch (e) { setError(e instanceof Error ? e.message : "사진을 올리지 못했어요."); } finally { setUploading(false); } }
  async function submit(event: React.FormEvent) { event.preventDefault(); setLoading(true); setError(""); setRecord(null); try { const body = type === "copy" ? { purpose, message, channel, photoPath } : type === "image" ? { purpose, photoPath: photoPath ?? "", title, dateText } : { noticeType, details }; const response = await fetch(`/api/generate/${type}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const json = await response.json(); if (!json.ok) throw new Error(json.error); setRecord(json.data); document.getElementById("results")?.scrollIntoView({ behavior: "smooth" }); } catch (e) { setError(e instanceof Error ? e.message : "결과를 만들지 못했어요."); } finally { setLoading(false); } }
  async function choose(index: number) { setSelected(index); if (record) await fetch(`/api/history/${record.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ selectedIndex: index }) }); }
  async function copyText(option: Option, index: number) { const text = `${option.text ?? option.title ?? ""}${Array.isArray(option.hashtags) ? `\n\n${option.hashtags.map((tag) => `#${tag}`).join(" ")}` : ""}`; await navigator.clipboard.writeText(text); setCopied(index); if (record) await fetch(`/api/history/${record.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ copied: true, selectedIndex: index }) }); }
  function download(option: Option, index: number) { const content = [option.title ?? option.headline, ...(Array.isArray(option.lines) ? option.lines : []), option.subline, option.dateText, option.footer].filter(Boolean).join("\n"); const blob = new Blob([content], { type: "text/plain;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `safil-${type}.txt`; anchor.click(); URL.revokeObjectURL(url); choose(index); if (record) fetch(`/api/history/${record.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ downloaded: true }) }); }

  return <div className="mx-auto flex max-w-4xl flex-col gap-8">
    <header className="reveal flex flex-col gap-4"><Link href="/" className="flex w-fit items-center gap-2 text-sm font-semibold text-muted hover:text-foreground"><ArrowLeft className="size-4" />홈으로</Link><div><p className="mb-2 text-sm font-bold text-primary">{info.eyebrow}</p><h1 className="text-balance text-3xl font-bold tracking-[-0.04em] sm:text-4xl">{info.title}</h1><p className="mt-3 max-w-2xl text-pretty text-sm leading-6 text-muted sm:text-base">{info.description}</p></div></header>
    <form onSubmit={submit} className="surface reveal reveal-delay-1 flex flex-col gap-7 rounded-[1.75rem] p-5 sm:p-8">
      {type !== "notice" && <fieldset className="flex flex-col gap-3"><legend className="mb-1 text-sm font-bold">어떤 소식인가요?</legend><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{purposes.map(([value,label]) => <button type="button" key={value} onClick={() => setPurpose(value)} className={`min-h-12 rounded-2xl border px-3 text-sm font-semibold transition-all ${purpose === value ? "border-foreground bg-foreground text-card" : "bg-card text-muted hover:border-primary/40 hover:text-foreground"}`}>{label}</button>)}</div></fieldset>}
      {type === "copy" && <><label className="flex flex-col gap-2"><span className="text-sm font-bold">홍보하고 싶은 내용</span><textarea className="field min-h-32 resize-y" value={message} maxLength={200} required placeholder="예: 이번 주말부터 제주 말차 크림 라테를 새로 선보여요" onChange={(e) => setMessage(e.target.value)} /></label><fieldset className="flex flex-col gap-3"><legend className="mb-1 text-sm font-bold">어디에 올릴까요?</legend><div className="grid grid-cols-2 gap-2">{[["instagram","인스타그램"],["naver_place","네이버 플레이스"]].map(([value,label]) => <button type="button" key={value} onClick={() => setChannel(value)} className={`min-h-12 rounded-2xl border text-sm font-semibold ${channel === value ? "border-foreground bg-foreground text-card" : "bg-card text-muted"}`}>{label}</button>)}</div></fieldset></>}
      {type === "image" && <><label className="flex flex-col gap-2"><span className="text-sm font-bold">메뉴 사진</span><span className={`flex min-h-44 cursor-pointer flex-col items-center justify-center gap-3 overflow-hidden rounded-[1.25rem] border border-dashed bg-background text-center transition-colors hover:border-primary ${photoUrl ? "p-2" : "p-6"}`}>{photoUrl ? <img src={photoUrl} alt="업로드한 메뉴 미리보기" className="max-h-64 w-full rounded-2xl object-cover" /> : <><ImagePlus className="size-7 text-primary" /><span className="text-sm font-semibold">사진을 선택하거나 끌어 놓으세요</span><span className="text-xs text-muted">JPG, PNG, WEBP · 최대 8MB</span></>}<input type="file" accept="image/jpeg,image/png,image/webp" className="sr-only" required={!photoPath} onChange={(e) => e.target.files?.[0] && upload(e.target.files[0])} /></span></label><div className="grid gap-4 sm:grid-cols-2"><label className="flex flex-col gap-2"><span className="text-sm font-bold">이미지 제목 <small className="font-normal text-muted">선택</small></span><input className="field" value={title} maxLength={60} placeholder="여름 한정 메뉴" onChange={(e) => setTitle(e.target.value)} /></label><label className="flex flex-col gap-2"><span className="text-sm font-bold">날짜 또는 기간 <small className="font-normal text-muted">선택</small></span><input className="field" value={dateText} maxLength={40} placeholder="7.20 - 8.31" onChange={(e) => setDateText(e.target.value)} /></label></div></>}
      {type === "notice" && <><fieldset className="flex flex-col gap-3"><legend className="mb-1 text-sm font-bold">어떤 안내인가요?</legend><div className="grid grid-cols-2 gap-2 sm:grid-cols-5">{noticeTypes.map(([value,label]) => <button type="button" key={value} onClick={() => setNoticeType(value)} className={`min-h-12 rounded-2xl border px-2 text-sm font-semibold ${noticeType === value ? "border-foreground bg-foreground text-card" : "bg-card text-muted"}`}>{label}</button>)}</div></fieldset><label className="flex flex-col gap-2"><span className="text-sm font-bold">손님께 안내할 내용</span><textarea className="field min-h-36 resize-y" value={details} required maxLength={300} placeholder="예: 와이파이 이름은 SAFIL_CAFE이고 비밀번호는 counter1234입니다" onChange={(e) => setDetails(e.target.value)} /></label></>}
      {error && <p role="alert" className="rounded-2xl bg-primary-soft px-4 py-3 text-sm font-semibold text-primary">{error}</p>}
      <button className="btn-primary w-full" disabled={loading || uploading}>{loading || uploading ? <><LoaderCircle className="spin size-5" />{uploading ? "사진 올리는 중" : "정성껏 만드는 중"}</> : <><Sparkles className="size-5" />{type === "copy" ? "문구 3가지 만들기" : type === "image" ? "디자인 2가지 만들기" : "안내물 2가지 만들기"}</>}</button>
    </form>
    {record && <section id="results" className="float-in flex scroll-mt-24 flex-col gap-5"><div><p className="text-sm font-bold text-primary">완성됐어요</p><h2 className="mt-1 text-2xl font-bold">마음에 드는 결과를 골라보세요</h2></div><div className="grid gap-4 md:grid-cols-2">{(record.options as Option[]).map((option,index) => <article key={index} className={`surface flex flex-col gap-5 rounded-[1.5rem] p-5 transition-all ${selected === index ? "border-primary ring-4 ring-primary-soft" : ""}`}><div className="flex items-center justify-between"><span className="text-xs font-bold text-primary">제안 {index + 1}</span>{selected === index && <span className="flex items-center gap-1 text-xs font-bold text-accent"><Check className="size-4" />선택됨</span>}</div>{type === "copy" ? <><p className="whitespace-pre-wrap text-sm leading-7">{String(option.text)}</p>{Array.isArray(option.hashtags) && <p className="text-sm font-medium text-primary">{option.hashtags.map((tag) => `#${tag}`).join(" ")}</p>}</> : <div className="flex aspect-[4/3] flex-col items-center justify-center gap-3 rounded-2xl bg-foreground p-6 text-center text-card"><strong className="text-balance text-2xl">{String(option.title ?? option.headline)}</strong>{Array.isArray(option.lines) ? option.lines.map((line) => <span key={String(line)} className="text-sm text-card/75">{String(line)}</span>) : <><span className="text-sm text-card/75">{String(option.subline ?? "")}</span><span className="text-xs font-bold text-primary-soft">{String(option.dateText ?? "")}</span></>}</div>}<p className="text-xs leading-5 text-muted">{String(option.reason ?? "")}</p><div className="flex gap-2">{type === "copy" ? <button type="button" className="btn-secondary flex-1 text-sm" onClick={() => copyText(option,index)}><Clipboard className="size-4" />{copied === index ? "복사했어요" : "문구 복사"}</button> : <button type="button" className="btn-secondary flex-1 text-sm" onClick={() => download(option,index)}><Download className="size-4" />다운로드</button>}<button type="button" className="btn-primary flex-1 text-sm" onClick={() => choose(index)}>{selected === index ? "선택 완료" : "이걸로 선택"}</button></div></article>)}</div></section>}
  </div>;
}
