ALTER TABLE cafe_profile ADD COLUMN IF NOT EXISTS atmosphere TEXT NOT NULL DEFAULT '';
ALTER TABLE cafe_profile ADD COLUMN IF NOT EXISTS vibe_tags JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE cafe_profile ADD COLUMN IF NOT EXISTS research_summary TEXT NOT NULL DEFAULT '';
ALTER TABLE cafe_profile ADD COLUMN IF NOT EXISTS research_sources JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE cafe_profile ADD COLUMN IF NOT EXISTS place_confirmed BOOLEAN NOT NULL DEFAULT FALSE;
