"use client";

import { useState } from "react";
import { Check, LoaderCircle, Plus, Save, Trash2 } from "lucide-react";
import type { CafeProfile, CafeProfileInput, Tone } from "@/lib/schemas";

const tones: Array<[Tone, string, string]> = [["warm", "따뜻하고 다정하게", "동네 단골에게 이야기하듯"], ["calm", "차분하고 정갈하게", "담백하고 편안한 느낌으로"], ["professional", "전문적이고 믿음직하게", "재료와 품질이 잘 보이도록"], ["witty", "위트 있고 경쾌하게", "재미있고 친근한 느낌으로"]];
const empty: CafeProfileInput = { name: "", location: "", concept: "", introduction: "", menus: [], tone: "warm", customerType: "", logoPath: null, photoPaths: [] };

export function ProfileForm({ initial }: { initial: CafeProfile | null }) {
  const [form, setForm] = useState<CafeProfileInput>(initial ?? empty); const [menu, setMenu] = useState("");
  const [saving, setSaving] = useState(false); const [saved, setSaved] = useState(false); const [error, setError] = useState("");
  const update = (key: keyof CafeProfileInput, value: CafeProfileInput[keyof CafeProfileInput]) => { setSaved(false); setForm((current) => ({ ...current, [key]: value })); };
  const addMenu = () => { const value = menu.trim(); if (value && !form.menus.includes(value)) { update("menus", [...form.menus, value]); setMenu(""); } };
  async function submit(event: React.FormEvent) { event.preventDefault(); setSaving(true); setError(""); try { const response = await fetch("/api/profile", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const json = await response.json(); if (!json.ok) throw new Error(json.error); setForm(json.data); setSaved(true); } catch (e) { setError(e instanceof Error ? e.message : "저장하지 못했어요."); } finally { setSaving(false); } }

  return <form onSubmit={submit} className="grid gap-6 lg:grid-cols-[1fr_.72fr]">
    <div className="flex flex-col gap-6">
      <section className="surface reveal reveal-delay-1 flex flex-col gap-6 rounded-[1.75rem] p-5 sm:p-7"><div><span className="text-xs font-bold text-primary">기본 정보</span><h2 className="mt-1 text-xl font-bold">카페를 소개해주세요</h2></div><div className="grid gap-5 sm:grid-cols-2"><label className="flex flex-col gap-2"><span className="text-sm font-bold">카페 이름</span><input className="field" required maxLength={60} placeholder="예: 사필 커피" value={form.name} onChange={(e) => update("name", e.target.value)} /></label><label className="flex flex-col gap-2"><span className="text-sm font-bold">위치</span><input className="field" required maxLength={120} placeholder="예: 서울 성수동" value={form.location} onChange={(e) => update("location", e.target.value)} /></label></div><label className="flex flex-col gap-2"><span className="text-sm font-bold">카페 콘셉트</span><input className="field" maxLength={200} placeholder="예: 직접 구운 디저트와 스페셜티 커피" value={form.concept} onChange={(e) => update("concept", e.target.value)} /></label><label className="flex flex-col gap-2"><span className="text-sm font-bold">짧은 소개</span><textarea className="field min-h-28 resize-y" maxLength={500} placeholder="우리 카페만의 이야기를 들려주세요" value={form.introduction} onChange={(e) => update("introduction", e.target.value)} /></label><label className="flex flex-col gap-2"><span className="text-sm font-bold">주요 손님</span><input className="field" maxLength={120} placeholder="예: 조용히 일하는 직장인과 동네 주민" value={form.customerType} onChange={(e) => update("customerType", e.target.value)} /></label></section>
      <section className="surface reveal reveal-delay-2 flex flex-col gap-5 rounded-[1.75rem] p-5 sm:p-7"><div><span className="text-xs font-bold text-primary">대표 메뉴</span><h2 className="mt-1 text-xl font-bold">자주 홍보할 메뉴</h2></div><div className="flex gap-2"><input className="field" value={menu} maxLength={60} placeholder="메뉴 이름 입력" onChange={(e) => setMenu(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter" && !e.nativeEvent.isComposing && e.keyCode !== 229) { e.preventDefault(); addMenu(); } }} /><button type="button" onClick={addMenu} className="btn-secondary shrink-0 px-4" aria-label="메뉴 추가"><Plus className="size-5" /></button></div>{form.menus.length > 0 ? <ul className="flex flex-wrap gap-2">{form.menus.map((item) => <li key={item} className="flex items-center gap-2 rounded-full bg-primary-soft py-2 pl-4 pr-2 text-sm font-semibold text-foreground">{item}<button type="button" onClick={() => update("menus", form.menus.filter((value) => value !== item))} className="flex size-7 items-center justify-center rounded-full hover:bg-card" aria-label={`${item} 삭제`}><Trash2 className="size-3.5" /></button></li>)}</ul> : <p className="text-sm text-muted">메뉴를 등록하면 홍보 문구가 더 구체적으로 만들어져요.</p>}</section>
    </div>
    <aside className="flex flex-col gap-6"><section className="surface reveal reveal-delay-2 flex flex-col gap-5 rounded-[1.75rem] p-5 sm:p-7"><div><span className="text-xs font-bold text-primary">말투 설정</span><h2 className="mt-1 text-xl font-bold">어떤 목소리로 말할까요?</h2></div><div className="flex flex-col gap-2">{tones.map(([value, title, description]) => <button type="button" key={value} onClick={() => update("tone", value)} className={`flex items-center justify-between rounded-2xl border p-4 text-left transition-all ${form.tone === value ? "border-foreground bg-foreground text-card" : "bg-card hover:border-primary/40"}`}><span><strong className="block text-sm">{title}</strong><small className={`mt-1 block ${form.tone === value ? "text-card/65" : "text-muted"}`}>{description}</small></span>{form.tone === value && <Check className="size-5" />}</button>)}</div></section><div className="sticky top-24 flex flex-col gap-3">{error && <p role="alert" className="rounded-2xl bg-primary-soft px-4 py-3 text-sm font-semibold text-primary">{error}</p>}{saved && <p role="status" className="flex items-center gap-2 rounded-2xl bg-primary-soft px-4 py-3 text-sm font-semibold text-accent"><Check className="size-4" />카페 정보를 저장했어요</p>}<button className="btn-primary w-full" disabled={saving}>{saving ? <LoaderCircle className="spin size-5" /> : <Save className="size-5" />}{saving ? "저장하는 중" : "카페 정보 저장"}</button><p className="text-center text-xs leading-5 text-muted">저장한 정보는 다음 홍보물부터 자동으로 반영돼요.</p></div></aside>
  </form>;
}
